PRO219_WebsiteBanDienThoai_FPhone/Controllers/AccountsController.cs
using AppData.Models;
using AppData.ViewModels.Accounts;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using PRO219_WebsiteBanDienThoai_FPhone.Services;
using PRO219_WebsiteBanDienThoai_FPhone.Models;
using AppData.FPhoneDbContexts;
using AppData.Repositories;
using AppData.IRepositories;
using AppData.IServices;
using AppData.Utilities;
using AppData.ViewModels;
using PRO219_WebsiteBanDienThoai_FPhone.ViewModel;
using Serilog;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using NuGet.Protocol.Plugins;
using System.Text;
using System.Data.Entity;
using System.Net.Mail;
using System.Net;

namespace PRO219_WebsiteBanDienThoai_FPhone.Controllers;

public class AccountsController : Controller
{
    private ICartDetailRepository _cartDetailepository;
    private IcartRepository _cartRepository;
    private FPhoneDbContext _context;
    private readonly HttpClient _client;
    private IEmailService _emailService;
    private IAccountService _service;
    private IHttpContextAccessor _accessor;
    public AccountsController(HttpClient client, IEmailService emailService, IAccountService service, IHttpContextAccessor accessor)
    {
        _cartDetailepository = new CartDetailepository();
        _cartRepository = new CartRepository();
        _context = new FPhoneDbContext();
        _client = client;
        _emailService = emailService;
        _service = service;
        _accessor = accessor;
    }
    //Khi đã đăng nhập ấn nút có biểu tượng user sẽ hiện ra profile của người dùng
    public async Task<IActionResult> Profile()
    {
        // lấy ra id người dùng khi đã đăng nhập
        var id = User.Claims.FirstOrDefault(claim => claim.Type == "Id")?.Value;
     
        ViewBag.idacount = id;
        // lấy ra thông tin người dùng thông qua id
        var datajson = await _client.GetStringAsync($"api/Accounts/get-user/{id}");
        var user = JsonConvert.DeserializeObject<AccountEntity>(datajson);
        if (user != null)
        {
            var jsondata = await _client.GetStringAsync($"api/Address/get-address/{id}");
            var address = JsonConvert.DeserializeObject<AddressEntity>(jsondata);
            // gộp địa chỉ
            if (address != null)
                ViewBag.Address = address.HomeAddress + ", " + address.District + ", " + address.City + ", " +
                                  address.Country;
            return View(user);
        }

        return View();
    }

    public IActionResult CreateAccount()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateAccount(ClAccountsViewModel model)
    {
        // lấy ra tài khoản admin để kiểm tra username có trùng hay không
        var result = await _client.GetStringAsync("/api/Accounts/get-all-staff");
        var userName = JsonConvert.DeserializeObject<List<ApplicationUser>>(result);
        //Kiểm tra username nhập vào có tồn tại trong list tài khoản admin
        if (userName.Any(c => c.UserName == model.Username))
        {
            ModelState.AddModelError("Username", "Tên đăng nhập đã tồn tại");
            return View(model);
        }

        if (model.Password == model.CfPassword)
        {
            model.ImageUrl = string.Empty;
            model.Points = 0;
            model.Status = 0;
            var respo = await _client.PostAsJsonAsync("/api/Accounts/SignUp/Client", model);
            // gán lại giá trị cho LoginModel để đăng nhập
            var login = new LoginModel();
            login.UserName = model.Username;
            login.Password = model.Password;
            //khi tạo tài khoản thành công sẽ đăng nhập luôn
            if (respo.IsSuccessStatusCode)
            {
                ObjectEmailInput emailInput = new ObjectEmailInput()
                {
                    FullName = model.Name,
                    SendTo = model.Email,
                    Subject = "Thông báo tạo tài khoản",
                    UserName = model.Username,
                    Message = Utility.EmailCreateAccountTemplate(model.Name, model.Username)
            };
                await _emailService.SendEmail(emailInput); // gửi email
                return await Login(login);
            }
        }
        else
        {
            ModelState.AddModelError("CfPassword", "Mật khẩu không trùng khớp");
            return View(model);
        }

        return View(model);
    }

    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginModel model)
    {
        DataError error = new DataError();
        var handler = new JwtSecurityTokenHandler();
        var result = await (await _client.PostAsJsonAsync("/api/Accounts/Login", model)).Content.ReadAsStringAsync();
        var respo = JsonConvert.DeserializeObject<LoginResponseVM>(result);
        if (respo != null && respo.Roles != null && respo.Token != null)
        {
            var token = respo.Token;
            var claimsPrincipal = handler.ReadJwtToken(token);
            var claims = claimsPrincipal.Claims.ToList();
            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, respo.Name));
            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

            // chuyển hướng đế trang admin
            if (respo.Roles.Contains("Admin") || respo.Roles.Contains("Staff"))
            {
                return RedirectPermanent("/admin/accounts/index");
            }
            else if (respo.Roles.Contains("User"))
            {

                return RedirectToAction("AddCart");
            }
            else
            {
                error.Success = false;
                error.Msg = "Tài khoản của bạn đã bị khóa, vui lòng liên hệ quản trị viên!";
                TempData["DataError"] = Utility.ConvertObjectToJson(error);
                return View(model);
            }

        }
        else
        {
            error.Success = false;
            error.Msg = "Sai tài khoản hoặc mật khẩu";
            TempData["DataError"] = Utility.ConvertObjectToJson(error);
            return View(model);
        }

        return NoContent();
    }
    public IActionResult checkoutID()
    {
        var userId = User.Claims.FirstOrDefault(claim => claim.Type == "Id")?.Value;
        
        if (userId == null)
        {
            TempData["SuccessMessage"] = "Bạn Phải Đăng nhập trước!";
            return RedirectToAction("Cart");
        }
       
        return RedirectToAction("Cart");
    }

    public IActionResult ResetPassword()
    {
        return View();
    }
    [HttpPost]
    public IActionResult ResetPassword(ResetPasswordViewModel model)
    {
       model.Data = _service.GetUserByEmail(model.Email);
        if (model.Data == null)
        {
            ModelState.AddModelError("Email", "Không có tài khoản nào được đăng ký với địa chỉ email này");
            return View(model);
        }
        else
        {
            return RedirectToAction("CheckUser", new { model.Email });
        }

    }

    public IActionResult ChangePassword()
    {   
        ChangePasswordViewmodel model = new ChangePasswordViewmodel();
        var idUser = User.Claims.FirstOrDefault(claim => claim.Type == "Id")?.Value;
       
        if (idUser != null) model.Data = _service.GetUserById(Guid.Parse(idUser));
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> ChangePassword(ChangePasswordViewmodel model)
    {
        Security security = new Security();
        var captchaSS = GetSessionValue("_captcha_value"); //lấy captcha từ session
        model.Data = _service.GetUserById(model.Data.Id);

        //validate mật khẩu cũ
        if (model.Data.Password != security.Encrypt("B3C1035D5744220E", model.OldPassword))
        {
            ModelState.AddModelError("OldPassword", "Mật khẩu không trùng khớp");
            return View(model);
        }
        //validate xác nhận mật khẩu
        if (model.CfPassword != model.NewPassword)
        {
            ModelState.AddModelError("CfPassword", "Mật khẩu không trùng khớp");
            return View(model);
        }

        if (captchaSS != null && captchaSS == model.Captcha) 
        {
            model.Data.Password = security.Encrypt("B3C1035D5744220E", model.NewPassword); // mã hoá mật khẩu để lưu vào database
            _service.UpdateUser(model.Data.Id, model.Data, out DataError error);
            if (error.Success)
            {
                //đăng xuất khi đổi mật khẩu thành công
                var authenticationProperties = new AuthenticationProperties
                {
                    ExpiresUtc = DateTimeOffset.UtcNow.AddSeconds(20) // Thiết lập thời gian hết hạn sau khi đăng xuất
                };
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme, authenticationProperties);
                _accessor.HttpContext.User = null; // xoá thông tin user
                //Gửi email

                ObjectEmailInput emailInput = new ObjectEmailInput()
                {
                    FullName = model.Data.Name,
                    SendTo = model.Data.Email,
                    Subject = "Thông báo đổi mật khẩu",
                    Message = Utility.EmailChangePasswordTemplate(model.Data.Name)
                };
                await _emailService.SendEmail(emailInput); // gửi email
                return View("~/Views/Accounts/Success.cshtml", "Đổi mật khẩu thành công. Vui lòng đăng nhập lại");
            }
            else
            {
                return View(model);

PRO219_WebsiteBanDienThoai_FPhone/Controllers/BlogsController.cs
using AppData.IServices;
using AppData.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRO219_WebsiteBanDienThoai_FPhone.ViewModel;

namespace PRO219_WebsiteBanDienThoai_FPhone.Controllers
{
    public class BlogsController : Controller
    {
        private readonly HttpClient _httpClient;
        private IBlogService _service;

        public BlogsController(HttpClient httpClient, IBlogService service)
        {
            _httpClient = httpClient;
            _service = service;
        }
        public IActionResult Index()
        {
            AdBlogViewModel model = new AdBlogViewModel();
            model.Records = _service.GetAll(model.SearchData, model.ListOptions);
            return View(model);
        }
        [HttpGet]

        public async Task<IActionResult> BlogDetail(Guid Id)
        {
            AdBlogViewModel model = new AdBlogViewModel();
            model.DetailModel = _service.Details(Id);
            model.Records = _service.GetAll(model.SearchData, model.ListOptions).Where(c =>c.Id!=Id).OrderByDescending(c =>c.CreatedDate).Take(3).ToList();
            return View(model);
        }
        public IActionResult BlogManagement()
        {
            return View();
        }
        public IActionResult CreateBlog()
        {
            return View();
        }
        public IActionResult BlogDetail()
        {
            return View();
        }
        public IActionResult EditBlog()
        {
            return View();
        }
        public IActionResult DeleteBlog() 
        { 
            return View(); 
        }

    }
}

PRO219_WebsiteBanDienThoai_FPhone/Controllers/ContactController.cs
using AppData.IServices;
using AppData.Models;
using AppData.Utilities;
using AppData.ViewModels;
using Microsoft.AspNetCore.Mvc;
using PRO219_WebsiteBanDienThoai_FPhone.ViewModel;

namespace PRO219_WebsiteBanDienThoai_FPhone.Controllers
{
    public class ContactController : Controller
    {
        private IContactService _service;

        public ContactController(IContactService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ContactViewModel obj)
        {
            var data = new ContactEntity();
            data.CODE = Utility.RandomString(8);
            data.FullName = obj.FullName;
            data.PhoneNumber = obj.PhoneNumber;
            data.Email = obj.Email;
            data.Address = obj.Address;
            data.Status = 0;
            data.Topic = obj.Topic;
            data.Content = obj.Content;
            data.CreateDate = DateTime.Now;
            data.Type = "LIEN_HE";
          var dbo=  _service.Add(data);
          if (dbo==null)
          {
              return View("DataError");
          }
        
          return View("Success");
        }
    }
}

PRO219_WebsiteBanDienThoai_FPhone/Controllers/DiscountController.cs
using AppData.FPhoneDbContexts;
using AppData.IServices;
using AppData.Models;
using AppData.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Web.Providers.Entities;
using static AppData.Utilities.Trangthai;

namespace PRO219_WebsiteBanDienThoai_FPhone.Controllers
{
  
        
    public class DiscountController : Controller
    {
        public readonly FPhoneDbContext _context;
        public readonly IDiscountServices _voucherSV;
       
        public readonly User user;
        public DiscountController(IDiscountServices discountServices , FPhoneDbContext fPhoneDb)
        {
            _context = fPhoneDb;
            _voucherSV = discountServices;
          
        }
        public async Task<IActionResult> Index()
        {
            var idNguoiDung = User.Claims.FirstOrDefault(claim => claim.Type == "Id")?.Value;
            if (string.IsNullOrEmpty(idNguoiDung))
            {
                ViewBag.NguoiDung = null;
            }
            else ViewBag.NguoiDung = idNguoiDung;
            return View();
        }
        public async Task<IActionResult> VoucherLstToCalm(string LoaiHinh)
        {
            var idNguoiDung = User.Claims.FirstOrDefault(claim => claim.Type == "Id")?.Value;
            if (string.IsNullOrEmpty(idNguoiDung))
            {
                ViewBag.NguoiDung = null;
            }
            else ViewBag.NguoiDung = idNguoiDung;

            var allVouchers = (await _voucherSV.GetallVoucher()).Where(c => c.StatusVoucher == "0" && c.Quantity > 0);
            switch (LoaiHinh)
            {
                case "TienMat":
                    allVouchers = allVouchers.Where(c => c.TypeVoucher == (int)TrangThaiLoaiKhuyenMai.TienMat);
                    break;
                case "PhanTram":
                    allVouchers = allVouchers.Where(c => c.TypeVoucher == (int)TrangThaiLoaiKhuyenMai.PhanTram);
                    break;
                case "FreeShip":
                    allVouchers = allVouchers.Where(c => c.TypeVoucher == (int)TrangThaiLoaiKhuyenMai.Freeship);
                    break;
                default:
                    break;
            }
            ViewBag.TatCaVoucher = allVouchers;
            return PartialView("_VoucherLstToCalm", allVouchers);
        }
        //public async Task<IActionResult> GetVoucherById(string idVoucher)
        //{
        //    var Voucher = await _voucherSV.get(idVoucher);
        //    double mucuidai = 0;
        //    string IdVoucher = "";
        //    int loaiuudai = 0;
        //    if (Voucher != null)
        //    {
        //        mucuidai = (double)Voucher.MucUuDai;
        //        IdVoucher = Voucher.IdVoucher;
        //        loaiuudai = (int)Voucher.LoaiHinhUuDai;
        //    }
        //    return Json(new { mucuidai, IdVoucher, loaiuudai });
        //}
        //public async Task<IActionResult> UpdateVoucherAfterUseIt(string idVoucher)
        //{
        //    var idNguoiDung = _userManager.GetUserId(User);
        //    if (await _voucherSV.UpdateVoucherAfterUseIt(idVoucher, idNguoiDung))
        //    {
        //        return Ok();
        //    }
        //    return BadRequest();
        //}
        //public async Task<IActionResult> UpdateVoucherSoluong(string idVoucher)
        //{
        //    if (await _voucherSV.UpdateVoucherSoluong(idVoucher))
        //    {
        //        return Ok();
        //    }
        //    return BadRequest();
        //}
        // GET: DiscountController

    }
}

PRO219_WebsiteBanDienThoai_FPhone/Views/Shared/DataError.cshtml
@using AppData.Utilities
@using AppData.ViewModels

@{
    string dataError_s = TempData["DataError"] as string;
    DataError dataError = !string.IsNullOrEmpty(dataError_s) ? Utility.ConvertJsonToObject<DataError>(dataError_s) : null;
}

@if (dataError != null)
{
    if (dataError.Msg != null)
    {
        if (dataError.Success)
        {
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                @dataError.Msg
            </div>
        }
        else
        {
            <div class="alert alert-danger alert-dismissible" style="margin-top:5px;">
                @dataError.Msg
                @if (dataError.MsgList != null && dataError.MsgList.Count > 0)
                {
                    <ul>
                        @foreach (var msgItem in dataError.MsgList)
                        {
                            <li>@msgItem</li>
                        }
                    </ul>
                }
            </div>
        }
    }
}

PRO219_WebsiteBanDienThoai_FPhone/Views/Shared/_Layout.cshtml
@using AppData.FPhoneDbContexts;
@using AppData.ViewModels.Phones;
@using PRO219_WebsiteBanDienThoai_FPhone.Services;
@using Microsoft.AspNetCore.Http;

@{
    var id = User.Claims.FirstOrDefault(claim => claim.Type == "Id")?.Value;
    FPhoneDbContext dbContext = new FPhoneDbContext();

}
@if (id == null)
{
    ViewBag.a = TempData["count"] is int countFromTempData ? countFromTempData : 0;
}
else{
    ViewBag.a = dbContext.CartDetails.Where(a => a.IdAccount == Guid.Parse(id)).Count();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PRO219_WebsiteBanDienThoai_FPhone</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <title>Bootstrap Example</title>
    <partial name="_LinkPartialView"/>
    <title>Phone Shop</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
@await Html.PartialAsync("_SideNavPartialView.cshtml")
<main role="main">
    @RenderBody()
</main>
@await Html.PartialAsync("_FooterPartialView.cshtml")

@*<!-- PopUp -->
<div class="popup hide__popup">
    <div class="popup__content">
        <div class="popup__close">
            <svg>
                <use xlink:href="/images/sprite.svg#icon-cross"></use>
            </svg>
        </div>
        <div class="popup__left">
            <div class="popup-img__container">
                <img class="popup__img" src="~/images/popup.jpg" alt="popup">
            </div>
        </div>
        <div class="popup__right">
            <div class="right__content">
                <h1>Get Discount <span>30%</span> Off</h1>
                <p>
                    Sign up to our newsletter and save 30% for you next purchase. No spam, we promise!
                </p>
                <form action="#">
                    <input type="email" placeholder="Enter your email..." class="popup__form">
                    <a href="#">Subscribe</a>
                </form>
            </div>
        </div>
    </div>
</div>*@

<!-- Go To -->

<partial name="_ScripPartialView"/>
<!-- JS -->

@await RenderSectionAsync("Scripts", false)
    <script>
        $(document).ready(async function () {
            $(window).on('unload', async function () {
                // Gửi yêu cầu POST đến máy chủ
                await $.ajax({
                    type: 'POST',
                    url: '/Home/OnBrowserClose'
                });
            });
        });
    </script>
</body>
</html>

PRO219_WebsiteBanDienThoai_FPhone/Views/Shared/_LinkPartialView.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>    
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
<!-- Main css -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;700&display=swap" rel="stylesheet" />
<link rel="shortcut icon" href="./images/favicon.ico" type="image/x-icon" />
<!-- Carousel -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.4.1/css/glide.core.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.4.1/css/glide.theme.min.css">
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<!-- Custom StyleSheet -->

<link rel="stylesheet" href="~/css/Phantrang.css" />
<link rel="stylesheet" href="~/css/styles.css" />
<link rel="stylesheet" href="~/css/Jquery.fancybox.min.css" />

PRO219_WebsiteBanDienThoai_FPhone/Views/Shared/_ScripPartialView.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.4.1/glide.min.js"></script>
<!-- Animate On Scroll -->
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Custom JavaScript -->
<script src="~/js/index.js"></script>
<script src="~/js/slider.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/jquery.fancybox.min.js"></script>

PRO219_WebsiteBanDienThoai_FPhone/Views/Shared/_SideNavPartialView.cshtml
@using AppData.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.Build.Framework
@using PRO219_WebsiteBanDienThoai_FPhone.Areas.Admin.Filters

@functions {

    public LoginModel? LoginModel { get; set; }
   
}

@{
    ViewData["Title"] = "_SideNavPartialView";
}
<style>
   /*  .btn{
        --bs-btn-font-size: 1.5rem;
    } */
</style>
<header id="header" class="header">
    <div class="navigation">
        <div class="container">
            <nav class="nav">
                <div class="nav__hamburger">
                    <svg>
                        <use xlink:href="/images/sprite.svg#icon-menu"></use>
                    </svg>
                </div>

                <div class="nav__logo">
                    <a asp-action="Index" asp-controller="Home">
                        FPHONE
                    </a>
                </div>

                <div class="nav__menu">
                    <div class="menu__top">
                        <span class="nav__category">PHONE</span>
                        <a href="#" class="close__toggle">
                            <svg>
                                <use xlink:href="./images/sprite.svg#icon-cross"></use>
                            </svg>
                        </a>
                    </div>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item mx-4 ">
                                    <a class="nav-link text-black" asp-action="Index" asp-controller="Home">Trang chủ</a>
                                </li>
                                <li class="nav-item mx-4">
                                    <a class="nav-link text-black" asp-action="Index" asp-controller="ListPhone">Sản phẩm</a>
                                </li>
                             @*    <li class="nav-item mx-4 ">
                                    <a class="nav-link text-black" asp-action="Index" asp-controller="Discount">Voucher</a>
                                </li> *@
                                <li class="nav-item mx-4">
                                    <a class="nav-link text-black" asp-action="Index" asp-controller="Blogs">Tin tức</a>
                                </li>
                                <li class="nav-item mx-4 ">
                                    <a class="nav-link text-black" asp-action="Index" asp-controller="Contact">Liên hệ</a>
                                </li>
                               
                            </ul>
                        </div>
                    </nav>
                </div>

                <div class="nav__icons">
                    @if (UserClaim.HasRole(User, "User"))
                    {
                        <a asp-action="Profile" asp-route-id="" asp-controller="Accounts" class="icon__item" id="">
                            <svg class="icon__user">
                                <use xlink:href="/images/sprite.svg#icon-user"></use>
                            </svg>
                        </a>
                    }
                    else if (!UserClaim.HasRole(User, "User"))
                    {
                        <a asp-controller="Accounts" asp-action="Login" class="icon__item" id="login-btn">
                            <svg class="icon__user">
                                <use xlink:href="/images/sprite.svg#icon-user"></use>
                            </svg>
                        </a>
                    }
                    <a href="#" class="icon__item" id="search-btn">
                        <svg class="icon__search">
                            <use xlink:href="/images/sprite.svg#icon-search"></use>
                        </svg>
                    </a>

                    <a asp-action="Cart" asp-controller="Accounts" class="icon__item" id="cart-btn">
                        <svg class="icon__cart">
                            <use xlink:href="/images/sprite.svg#icon-shopping-basket"></use>
                        </svg>

                        <span style="background-color: chocolate; " id="cart__total">@ViewBag.a</span>
                    </a>
                </div>
            </nav>
        </div>
    </div>
    

    @* <div class="auth">
        <form asp-action="Login" asp-controller="Accounts" class="login-form">
            <h3>Đăng nhập</h3>
            <partial name="DataError"/>
            <input required type="text" asp-for="@LoginModel.UserName" name="UserName" placeholder="Tên đăng nhập" class="box">
            <input required type="password" asp-for="@LoginModel.Password" name="Password" placeholder="Mật khẩu" class="box">
            <p>Quên mật khẩu <a asp-action="ResetPassword" asp-controller="Accounts">Click Here</a></p>
            <p>Không có tài khoản ? <a asp-controller="Accounts" asp-action="CreateAccount">Tạo mới</a></p>
            <input type="submit" value="Đăng nhập" class="btn border" >
        </form>
    </div> *@
    <div class="searchF">
        <form action="" class="search-form">
            <input type="search" id="search-box" placeholder="Search here..">
            <label for="search-box" class="fas fa-search"></label>
        </form>
    </div>

</header>